### ISSUE TITLE
CyberKit Won’t Work iOS 13.1.3 Page Are not Loading And The CyberKit Browser Crashes

### ISSUE THREAD

**Issue by miguelr4720** [UInt2048/CyberKit#24] opened 2023-12-20 16:28 UTC
CyberKit Does Not Work 13.1.3 The Page are Loading Slow and No Images are Showing on the Website and Browser Also Crashes When Going into Setting in the CyberKit Please Fix ASAP

**Comment by UInt2048** [comment] 2024-01-27 16:15
Duplicate of #12

**Closed as not planned by UInt2048** 2024-01-27 16:15 UTC
Labels: K: Duplicate, 13.x
