### ISSUE TITLE
Cyberkit minibrowser not working on iOS 12 iPhone XS max 512gb

### ISSUE THREAD

**Issue by bloodyrists** [UInt2048/CyberKit#25] opened 2024-01-09 00:06 UTC
Ayo

So basically all I get upon launching is a blank page. Whenever I type google or some other website (I did try typing full url) in the the address bar and click go some zalgo text appears for a split second and then returns to being blank.

Do you know why it's doing that?

**Comment by UInt2048** [comment] 2024-01-09 16:04
Seems like a duplicate of #15

**Closed as not planned by UInt2048** 2024-01-09 16:04 UTC
Labels: K: Duplicate, 12.x
