### ISSUE TITLE
Websites not loading [TrollStore 15.5b4]

### ISSUE THREAD

**Issue by Delamcode** [UInt2048/CyberKit#18] opened 2023-09-14 15:22 UTC
Mostly just wanted to test this out. I first tried the full version and it installed but crashed. I also tried with ESign+ to use the TrollStore Install just in case, and that version didn’t crash. However whenever I tried to enter a website it wouldn’t even try to open the website. I guessed maybe it was just a problem with this version. I then installed the mini version and it did install and open with TrollStore (not ESign+), but the websites STILL wouldn’t try to load. Not sure what to try from here…
I’m using an iPad Air 5 on 15.5b4.

**Comment by UInt2048** [comment] 2023-09-14 17:16
Jetsam configuration is required.

I’m afraid it’s currently unknown how to do so on rootless iOS (see #10) and I don’t have a device where I can experiment myself yet.

**Comment by Delamcode** [comment] 2023-09-14 17:24
Interesting. That’s unfortunate. Could you also explain/point me to an explanation about why jetsam configurations are required? Just wondering, as I now understand that it’s not possible to run on rootless.

**Comment by UInt2048** [comment] 2023-09-14 18:37
@Delamcode The normal jetsam limits per-process are woefully inadequate for WebKit’s purposes. iOS resolves this with special exemptions for WebKit, and therefore CyberKit requires them too.

Unfortunately, I don’t currently know how to give my XPC services this exemption with a tweak, and thus I’m in a bind on rootless.

**Comment by UInt2048** [comment] 2023-09-16 17:54
Closing as duplicate of #10

**Closed by UInt2048** 2023-09-16 17:54 UTC

**Comment by UInt2048** [comment] 2023-10-01 23:31
Duplicate of #10

As per the discussion there, legacy jetsam configuration does not exist in 0.0.9 or later.

Documentation has been improved in previous releases to explain its purpose.
