### ISSUE TITLE
13.5 Sites taking forever to load

### ISSUE THREAD

**Issue by gummykage** [UInt2048/CyberKit#17] opened 2023-08-05 13:53 UTC
Installed PlistBuddy, Installed Jetsam configurator, Installed Cyberkit Fennec (iOS 13) from Ulnt2048 repo. Cyberkit(Firefox) app trying to load disney.com has taken over 2 mins to load just the logo. Tried apple.com took 4 mins to load just the top bar.

**Comment by UInt2048** [comment] 2023-08-15 09:23
Duplicate of #12

**Closed by UInt2048** 2023-08-15 09:23 UTC
Labels: duplicate

**Comment by bizbuzzone** [comment] 2026-02-24 03:20
## Canvas Capture Page Created

**File**: \`tools/canvas_capture.html\` — comprehensive canvas fingerprint capture tool (34KB, self-contained)

### 4 Tests Included:
1. **BrowserLeaks Canvas** — exact replication of browserleaks.com draw sequence
2. **FingerprintJS Canvas** — arcs, gradients, shadows, composite operations
3. **CreepJS Canvas** — bezier curves, emoji, radial gradients, dashed lines
4. **WebGL Canvas** — GPU triangle + renderer/vendor/extension capture

### Captures Per Test:
- Full \`toDataURL('image/png')\` base64 string
- MD5 hash of the data URL
- First 100 pixels as \`#RRGGBBAA\` hex values
- Canvas dimensions, non-transparent pixel count, timing

### Usage:
1. Open on **iPhone 14 iOS 26.3** → save all output as reference
2. Open on **iPhone 14 iOS 16.1.1** → save output for same hardware baseline  
3. Open on **CK26 devices** (iPhone 13 Pro, iPhone 12 Pro) → capture current hashes
4. Compare MD5 hashes and pixel data between iOS 16 and iOS 26 on same hardware
5. Use real iOS 26 toDataURL PNG data for Approach A (hash substitution)
