### ISSUE TITLE
CyberKit Fennec crashes on parsing URLs

### ISSUE THREAD

**Issue by shivsey** [UInt2048/CyberKit#11] opened 2023-07-13 12:38 UTC
I am now able to launch CyberKit but upon loading any website it crashes.  I’m able to navigate the settings and the homepage loads thumbnails for the various sites, but clicking on any link or loading any URL enter in the navigation bar ends up crashing the program.

Not sure if the crash log helps but here it is

[text.txt](https://github.com/UInt2048/CyberKit/files/12039411/text.txt)

**Comment by UInt2048** [comment] 2023-07-13 22:31
@shivsey Just to make sure, you're not using a third-party keyboard, right?

**Comment by shivsey** [comment] 2023-07-14 02:41
Nope, but here’s a list of all the packages I have installed

3DAppVersionSpoofer:(com.0xkuj.3dappversionspoofer) 1.1.4
7-zip (POSIX):(p7zip) 17.04
Alderis Color Picker:(ws.hbang.alderis) 1.2.3
AltDaemon:(com.rileytestut.altdaemon) 1.0.1
AltList:(com.opa334.altlist) 1.0.10
AppData:(com.fouadraheb.appdata) 1.4.0
AppStore++:(com.cokepokes.appstoreplusplus) 0.10.1-5
apt:(apt) 2.6.0-1
AutoUnlockX:(com.spark.autounlockx) 1.0.16
Base Structure:(base) 1-5
bash:(bash) 5.2.0
BlankIcons:(com.nrkvv.blankicons) 0.1.1
ca-certificates:(ca-certificates) 20230417
CCSupport:(com.opa334.ccsupport) 1.3.10-2
Cephei Tweak Support:(ws.hbang.common) 1.17.1
Chariz APT Keyring:(chariz-keyring) 2021.07.18
coreutils:(coreutils) 9.3-1
Cr4shed:(com.muirey03.cr4shed) 4.3.0
curl:(curl) 7.88.1
CyberKit MobileMiniBrowser (iOS 14):(com.matthewbenedict.mobileminibrowser+14) 0.0.7-alpha
darwintools:(darwintools) 1.5
dash:(dash) 0.5.11.4
debianutils:(debianutils) 5.7-1
diffutils:(diffutils) 3.8
dimentio:(dimentio) 1:0~20230202.7ffffff
diskdev-cmds:(diskdev-cmds) 697
dpkg:(dpkg) 1.21.21
EntitlementFix:(in.net.mario.tweak.fixentitlement) 0.0.3
essential:(essential) 0-5
EvilScheme:(net.pane.l.evilscheme) 19.07.2002
file-cmds:(file-cmds) 400-1
Filza File Manager 64-bit:(com.tigisoftware.filza64bit) 4.0.1-4
findutils:(findutils) 4.8.0-1
Flex 3 Beta:(flex3beta) 1:3~Beta98
gpgv:(gpgv) 2.3.6
grep:(grep) 3.10-1
gzip:(gzip) 1.12
havoc-keyring:(havoc-keyring) 2022.06.03
HookKit Framework:(me.jjolano.fmwk.hookkit) 1.0.15
HookKit Module (Cydia Substrate):(me.jjolano.hkmodule.substrate) 1.0.8
HookKit Module (fishhook):(me.jjolano.hkmodule.fishhook) 1.0.8
iPhone Firmware (/sbin):(firmware-sbin) 0-2
iSponsorBlock:(com.galacticdev.isponsorblock) 1.2
launchctl:(launchctl) 1:1.1.1
libapt-pkg6.0:(libapt-pkg6.0) 2.6.0-1
libassuan0:(libassuan0) 2.5.5
libbrotli1:(libbrotli1) 1.0.9
libc-ares2:(libc-ares2) 1.19.0
libcrypt2:(libcrypt2) 4.4.33
libcurl4:(libcurl4) 7.88.1
libdimentio0:(libdimentio0) 1:0~20230202.7ffffff
libedit0:(libedit0) 3.1-20221030
libffi7:(libffi7) 3.3-1
libffi8:(libffi8) 3.4.2
libgcrypt20:(libgcrypt20) 1.10.1
libgmp10:(libgmp10) 6.2.1-3
libgnutls30:(libgnutls30) 3.8.0
libgpg-error0:(libgpg-error0) 1.46
libhogweed6:(libhogweed6) 3.8.1
libhooker:(org.coolstar.libhooker) 1.6.9
libidn2-0:(libidn2-0) 2.3.4
libintl8:(libintl8) 0.21.1
libiosexec1:(libiosexec1) 1.3.1
libkernrw0:(libkernrw0) 1.0-1
liblz4-1:(liblz4-1) 1.9.3
liblzma5:(liblzma5) 5.4.1
libmd0:(libmd0) 1.0.4-1
libMRYIPC:(com.muirey03.libmryipc) 2.0.1
libncursesw6:(libncursesw6) 6.4
libnettle8:(libnettle8) 3.8.1
libnghttp2-14:(libnghttp2-14) 1.52.0
libp11-kit0:(libp11-kit0) 0.24.1
libpam-modules:(libpam-modules) 1000.0
libpam2:(libpam2) 20190224
libpcre1:(libpcre1) 8.45-1
libpcre2-8-0:(libpcre2-8-0) 10.40
libreadline8:(libreadline8) 8.2.0
librtmp1:(librtmp1) 2.4+20151223.gitfa8646d.1
libSandy:(com.opa334.libsandy) 1.1.1
libSparkAppList:(com.spark.libsparkapplist) 1.0.10
libssh2-1:(libssh2-1) 1.10.0-1
libssl3:(libssl3) 3.0.8
libtasn1-6:(libtasn1-6) 4.18.0
libundirect:(com.opa334.libundirect) 1.1.4-3
libunistring2:(libunistring2) 0.9.10-2
libunistring5:(libunistring5) 1.1
libxxhash0:(libxxhash0) 0.8.1
libz-ng2:(libz-ng2) 2.0.6
libzstd1:(libzstd1) 1.5.5
Loupe:(com.udevs.loupe) 1.2.1
LowerInstall:(com.julioverne.lowerinstall) 0.0~beta6
Modulous Framework:(me.jjolano.fmwk.modulous) 1.0.8
MYbloXX® (iOS 14+):(net.myxxdev.mybloxx14) 4.020822-14
ncurses-bin:(ncurses-bin) 6.4
ncurses-term:(ncurses-term) 6.4
New GNU Portable Threads:(libnpth0) 1.6-2
NoMoreSmallApps:(com.spark.nomoresmallapps) 2.0.1
NoScrollbarGrabDelay:(com.nscake.noscrollbargrabdelay) 0.0.1
Omni:(com.reddit.omni) 7.0-13+debug
plutil:(plutil) 0.2.2-1
PowerSelector:(com.ichitaso.powerselector11) 1.3.9
PreferenceLoader:(preferenceloader) 3.0.3
procursus-keyring:(procursus-keyring) 2020.05.09-4
Profile Directory:(profile.d) 0-7
RocketBootstrap:(com.rpetrich.rocketbootstrap) 1.1.0~libhooker2
RootBridge Framework:(me.jjolano.fmwk.rootbridge) 1.0.1
Safe Mode (libhooker):(org.coolstar.safemode) 1.1.4
sed:(sed) 4.9
Sentinel:(com.megadev.sentinel) 1.3.2
Shadow:(me.jjolano.shadow) 3.7.6
shell-cmds:(shell-cmds) 278-2
shshd:(shshd) 1.1.1.1
Sileo:(org.coolstar.sileo) 2.5
snaputil:(snaputil) 12.1
sudo:(sudo) 1.9.12p2
System Info:(xyz.xninja.systeminfo) 2.7.2-2
system-cmds:(system-cmds) 880.60.2-1
tar:(tar) 1.34
TrollStore Helper:(com.opa334.trollstorehelper) 1.5.1
TSS Saver:(com.1conan.tsssaver) 2.0.5-1
uikittools:(uikittools) 2.1.6-1
unrar:(unrar) 6.2.6
unzip:(unzip) 6.0-28
xz-utils:(xz-utils) 5.4.1
YTReExplore:(com.ps.ytreexplore) 1.0.2
YTUHD:(com.ps.ytuhd) 1.4.0
YTUnShorts:(com.ps.ytunshorts) 1.0.1
zip:(zip) 3.0-11
zsh:(zsh) 5.9

**Comment by UInt2048** [comment] 2023-07-17 00:00
@shivsey Thanks for the report. I have reproduced the issue and implemented a fix locally.

It turns out that in bundling internationalization during iOS 12 support, I forgot to also have the internationalization file be copied in Fennec. Its absence caused a crash in `URLParser::internationalDomainNameTranscoder()`.

**Comment by UInt2048** [comment] 2023-07-17 13:18
Fixed in v0.0.8 alpha

**Closed by UInt2048** 2023-07-17 13:18 UTC
Labels: regression
